Easy/Easy/Controllers/CandidateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Easy.Core;
using Easy.Data;
using Easy.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Easy.Controllers
{
    [Route("api/[controller]")]
    public class CandidateController : Controller
    {
        IRepository Repository { get; }
        public CandidateController(IRepository repository)
        {
            Repository = repository;
        }

        // GET: api/<controller>
        [HttpGet]
        public object Get()
        {
            var result = Repository.Candidates
                    .Include(p => p.Account)
                    .Include(p => p.Skills)
                    .Include(p => p.Address)
                    .Include(p => p.Phones)
                    .ToArray();

            return new {
                Model = result,
                Success = true
            };
        }

        // GET api/<controller>/5
        [HttpGet("{id}")]
        public string Get(int id)
        {
            return "value";
        }

        // POST api/<controller>
        [HttpPost]
        public JsonResult Post([FromBody]Candidate candidate)
        {
            Repository.Save(candidate);
            return this.AsSuccessJsonResult(candidate);
        }

        // PUT api/<controller>/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/<controller>/5
        [HttpDelete("{id}")]
        public IActionResult Delete(int id)
        {
            var candidate = Repository.Candidates
                .Include(p => p.Account)
                .Include(p => p.Address)
                .Include(p => p.Skills)
                .Include(p => p.Phones)
                .FirstOrDefault(s => s.Id == id);
            if (candidate == null)
                return NotFound("The candidate was not found");
            Repository.Delete(candidate);
            return Ok();
        }
    }
}

Easy/Easy/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Easy.Core;
using Easy.Data;
using Easy.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace Easy.Controllers
{
    public class HomeController : Controller
    {
        IRepository Repository { get; }

        public HomeController(IRepository repository)
        {
            Repository = repository;
        }

        public IActionResult Index()
        {
            var lista = Repository.Candidates.ToList();
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }

        // POST: /<controller>/AddPhone
        [HttpPost]
        public JsonResult AddPhone([FromBody]Phone phone)
        {
            if (ModelState.IsValid && phone.CandidateId > 0)
                Repository.Save(phone);


            return this.AsSuccessJsonResult(phone);
        }

        // POST: /<controller>/RemovePhone
        [HttpPost]
        public JsonResult RemovePhone([FromBody]Phone phone)
        {
            if (phone.Id > 0)
                Repository.Delete(phone);
            return this.AsSuccessJsonResult(phone);
        }

        // POST: /<controller>/AddSkill
        [HttpPost]
        public JsonResult AddSkill([FromBody]Skill skill)
        {
            if (skill.CandidateId > 0)
                Repository.Save(skill);
            return this.AsSuccessJsonResult(skill);
        }

        // POST: /<controller>/RemoveSkill
        [HttpPost]
        public JsonResult RemoveSkill([FromBody]Skill skill)
        {
            if (skill.Id > 0)
                Repository.Delete(skill);
            return this.AsSuccessJsonResult(skill);
        }

        // POST: /<controller>/Save
        [HttpPost]
        public JsonResult Save([FromBody]Candidate candidate)
        {
            Repository.Save(candidate);            
            return this.AsSuccessJsonResult(candidate);
        }
    }
}

Easy/Easy/Controllers/ResumeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Easy.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Easy.Controllers
{
    public class ResumeController : Controller
    {
        IRepository Repository { get; }
        public ResumeController(IRepository repository)
        {
            Repository = repository;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [Route("/[controller]/{id}")]
        [Route("/[controller]/edit/{id}")]
        public IActionResult Edit(int id)
        {
            if (id == 0 || !Repository.Candidates.Any(a => a.Id == id))
                return NotFound();
            var candidate = Repository.Candidates
                    .Include(i => i.Address)
                    .Include(i => i.Account)
                    .Include(i => i.Phones)
                    .Include(i => i.Skills)
                    .First(item => item.Id == id);            
            return View(candidate);
        }

        public JsonResult Get()
        {
            var result = Repository.Candidates
                    .Include(p => p.Account)
                    .Include(p => p.Skills)
                    .Include(p => p.Address)
                    .Include(p => p.Phones)
                    .ToArray();
            return Json(result);
        }
    }
}

Easy/Easy/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Easy/Easy/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Easy/Easy/Views/Home/Index.cshtml

@{
    ViewData["Title"] = "Home Page";
}
@Html.Partial("../Resume/CreateOrEdit")

@section scripts{
    @Html.Partial("../Shared/_IncludeResumeScript")
}

Easy/Easy/Views/Resume/CreateOrEdit.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<style>
    div[ng-form].ng-submitted .link-invalid-option {
        color: #b75755 !important;
        font-weight: bold;
    }

    div[ng-form].ng-submitted input[class*='ng-invalid'] {
        border-radius: 5px;
        border: #cc5f5f 1px solid;
        background-color: #f2dede;
        color: #b75755;
    }

    div[ng-form].ng-submitted table.ng-invalid-length {
        border-radius: 5px;
        background-color: #f2dede;
        color: #b75755;
    }

    input.ng-dirty.ng-invalid-required {
        border-radius: 5px;
        border: #cc5f5f 1px solid;
        background-color: #f2dede;
        color: #b75755;
    }

    .required {
        color: red;
    }
</style>

<div ng-app="app" ng-form="frmResume">
    <div class="row tab-content" ng-controller="CandidateController as controller">
        <div class="row">
            <alert id="alert" name="alert"></alert>
            <nav class="navbar navbar-default navbar-fixed-bottom">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="collapsed navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-7" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
                        </button> <a href="#" class="navbar-brand">&copy; 2017 - Easycomtec</a>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-7">
                        <ul class="nav navbar-nav">
                            <li class="active"><a data-toggle="tab" href="#personalData" ng-class="controller.profileFormIsValid(frmResume) ? '' : 'link-invalid-option'">Personal data</a></li>
                            <li><a data-toggle="tab" href="#contactData" ng-class="frmResume.Phones.$valid === false ? 'link-invalid-option' : ''">Contact</a></li>
                            <li><a data-toggle="tab" href="#skillData" ng-class="frmResume.Skills.$valid === false ? 'link-invalid-option' : ''">Skills</a></li>
                        </ul>
                        <form class="navbar-form navbar-left pull-left">
                            <button type="button" ng-click="controller.saveProfile(frmResume)" class="btn btn-success">Save Profile</button>
                            @*ng-disabled="!frmResume.$valid"*@
                        </form>
                    </div>
                </div>
            </nav>
        </div>
        <div id="personalData" class="tab-pane fade in active">
            <script type="in/Login" class="btn" redirect-uri="http://localhost:52860">
            </script>
            <div class="panel panel-default">
                <div class="panel-heading"><h4>Basic Info</h4></div>
                <div class="panel-body">
                    <input id="Id" name="Id" type="hidden" />
                    <div class="form-group">
                        <span class="required">*</span>
                        <label for="Name">Name</label>
                        <input type="text" id="Name" name="Name" ng-model="controller.candidate.Name" class="form-control" ng-required="true" />
                    </div>
                    <div class="form-group">
                        <span class="required">*</span>
                        <label for="BirthDate">Birth Date</label>
                        <input type="date" id="BirthDate" name="BirthDate" ng-model="controller.candidate.BirthDate" class="form-control" ng-required="true" />
                    </div>
                    <div class="form-group">
                        <span class="required">*</span>
                        <label for="Email">Email</label>
                        <input type="email" id="Email" nam e="Email" ng-model="controller.candidate.Account.Email" class="form-control" ng-required="true" />
                    </div>
                </div>
            </div>
            @*</div>
                <div id="addressData" class="tab-pane fade">*@
            <div class="panel panel-default">
                <div class="panel-heading"><h4>Address Info</h4></div>
                <div class="panel-body">
                    <div class="form-group">
                        <span class="required">*</span>
                        <label for="Name">Country</label>
                        <input type="text" id="Country" name="Country" ng-model="controller.candidate.Address.Country" class="form-control" ng-required="true" />
                    </div>
                    <div class="form-group">
                        <span class="required">*</span>
                        <label for="Name">State</label>
                        <input type="text" id="State" name="State" ng-model="controller.candidate.Address.State" class="form-control" ng-required="true" />
                    </div>
                    <div class="form-group">
                        <span class="required">*</span>
                        <label for="Name">City</label>
                        <input type="text" id="City" name="City" ng-model="controller.candidate.Address.City" class="form-control" ng-required="true" />
                    </div>
                    <div class="form-group">
                        <label for="Name">Number</label>
                        <input type="text" id="Number" name="Number" ng-model="controller.candidate.Address.Number" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="Name">Postal Code</label>
                        <input type="text" id="PostalCode" name="PostalCode" ng-model="controller.candidate.Address.PostalCode" class="form-control" ng-pattern="/^(\d{5}(-\d{3,4})?|[A-Z]\d[A-Z] *\d[A-Z]\d)$/" />
                    </div>
                </div>
            </div>
        </div>
        <div id="contactData" class="tab-pane fade">
            <phone phones="controller.candidate.Phones" add-phone="controller.addPhone(phone)" remove-phone="controller.removePhone(phone)"></phone>
        </div>
        <div id="skillData" class="tab-pane fade">
            <skill skills="controller.candidate.Skills" add-skill="controller.addSkill(skill)" remove-skill="controller.removeSkill(skill)"></skill>
        </div>

    </div>
</div>

Easy/Easy/Views/Resume/Edit.cshtml
@model Easy.Core.Candidate
@using Easy.Extensions
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("../Resume/CreateOrEdit")

@section scripts{
    @Html.Partial("../Shared/_IncludeResumeScript")
    <script src="~/js/providers/JsonDatetimeParseProvider.js"></script>

    <script>
        function onCandidateLoad(candidate) {
            return JSON.parse('@Html.Raw(this.Model.ToSafelyJson())', JSON.dateParser);
        }
    </script>
}

Easy/Easy/Views/Resume/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div ng-app="app" ng-form="frmResume" ng-controller="customersCtrl">
    <alert id="alert" name="alert"></alert>
    <table class="table table-striped table-hover table-responsive">
        <thead>
            <tr>
                <th>Name</th>
                <th>E-mail</th>
            </tr>
        </thead>
        <tr ng-repeat="x in resumes">
            <td>{{ x.Name }}</td>
            <td>{{ x.Account.Email }}</td>
            <td>
                <div class="btn-group pull-right" role="group" aria-label="Basic example">
                    <button type="button" class="btn btn-danger" ng-click="delete(x.Id)">remove</button>
                    <button type="button" class="btn btn-success" ng-click="edit(x.Id)">edit resume</button>
                    @*<button type="button" class="btn btn-secondary">Right</button>*@
                </div>
            </td>
        </tr>
    </table>
</div>


@section Scripts{
    <script src="~/js/services/httpService.js"></script>
    <script>

        window.registerToAngular(function (app) {
            app.controller('customersCtrl', function ($scope, $httpClient, UserNotification) {
                $scope.resumes = [];

                $scope.edit = function (id) {
                    window.location.href = '/Resume/' + id;
                }

                $scope.delete = function (id) {
                    $httpClient
                        .deleteAsync("/api/candidate/" + id)
                        .Success(function (response) {
                            var index = $scope.resumes.findIndex((item) => item.Id == id);
                            if (index > -1)
                                $scope.resumes.splice(index, 1);
                            UserNotification.Instance.Success("Item deleted with success!", "Information");
                        }).Fail(function (response) {
                            UserNotification.Instance.Error(response.MessageError, "Error");
                        });
                }

                $httpClient.getAsync("/api/candidate")
                    .Success(function (response) {
                        $scope.resumes = response.data.Model;
                    });
            });
        });
    </script>
}

Easy/Easy/Views/Shared/_IncludeResumeScript.cshtml
@*<script type="text/javascript" src="//platform.linkedin.com/in.js">
        api_key: 78solhtvuzyg33
        authorize: true
        onLoad: onLinkedInLoad
    </script>*@
<script src="~/js/providers/LinkedIn.js"></script>
<script src="~/js/validators/tableValidator.js"></script>
<script src="~/js/services/httpService.js"></script>
<script src="~/js/services/candidateService.js"></script>
<script src="~/js/services/skillService.js"></script>
<script src="~/js/user.js"></script>
<script src="~/js/skill.js"></script>
<script src="~/js/phone.js"></script>
<script>

        // Setup an event listener to make an API call once auth is complete
        function onLinkedInLoad() {

            $("span[id*='-title-text'").html("Use Linkedin profile");
            //IN.UI.Authorize().params({"scope":["r_basicprofile", "r_emailaddress", "r_contactinfo"]});
            IN.UI.Authorize().place();
            IN.Event.on(IN, 'auth', getProfileData);
            //IN.Event.on(IN, "auth", getProfileData);
        }

        // Handle the successful return from the API call
        function onSuccess(data) {
            console.log(data);
        }

        // Handle an error response from the API call
        function onError(error) {
            console.log(error);
        }

        // Use the API call wrapper to request the member's basic profile data
        function getProfileData() {
            //IN.API.Raw("/people/~").result(onSuccess).error(onError);
            IN.API.Profile("me").fields("id,firstName,lastName,phone-numbers,email-address,picture-urls::(original),public-profile-url,location:(name)").result(function (me) {
                var profile = me.values[0];
                var id = profile.id;
                var firstName = profile.firstName;
                var lastName = profile.lastName;
                var emailAddress = profile.emailAddress;
                var pictureUrl = profile.pictureUrls.values[0];
                var profileUrl = profile.publicProfileUrl;
                var country = profile.location.name;
            });
        }

</script>

Easy/Easy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Easy.Client</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color:#602c2c">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Easy.Client</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Resume" asp-action="Index">Resumes</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @*<hr />*@
    </div>
    @*<footer>
        <p>&copy; 2017 - Easy.Client</p>
    </footer>*@
    
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.0/angular.min.js"></script>
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>